### ISSUE TITLE
项目被培训机构利用

### ISSUE THREAD

**Issue by GaoQ1** [qhduan/just_another_seq2seq#13]
朋友，你这个项目被某培训机构拿去讲课利用了

**Comment by qhduan** [comment]
感谢这位朋友的提醒

首先很抱歉最近repo都没更新，工作原因导致某些自己的开源项目相关开发放缓了。

---

其实理论上来说，本项目没有license，而github对于没有license的repo默认的处理是比较严格的，也就是严格来说本项目“不是开源项目”， https://choosealicense.com/no-permission/

不过一般来说，我把自己的项目都当做类似MIT许可的项目（只是类似，毕竟我没添加，我就算现在添加，也并不影响添加前的代码协议）

以MIT协议来考虑（虽然本repo现在不是），其实有任何人在添加引用声明的情况下，我并不在意代码被在任何情况下使用，包括而不限于商业使用

---

其实我更加在意的是，别人怎么看待我写的代码的，如果有人说我写的很糟糕，我倒是比较有兴趣啦

最近倒是有人联系我在他自作的书、教程中是否可以有来源声明的使用我的代码，我也是允许过的，不知道是不是你说的就是了

我觉得这种事情说明白了，也并不是什么禁忌，其实我倒是很好奇怎么“利用”我的代码的，如果没有其他问题，我很想去看看

最后再次感谢

**Comment by GaoQ1** [comment]
开源精神很欣赏，若个人学习使用倒没什么大碍。但是用于商用教学，还不做来源声明，不知是否造成侵权。我所谓的“利用”就是他们拿你代码原封不动的用于教学项目。

**Comment by qhduan** [comment]
理论上是不行，实际上也只能是知会或谴责

**Comment by GaoQ1** [comment]
就看你追不追究了，但很感谢你的项目，学到很多东西。

**Comment by ily666666** [comment]
兄弟，是慕课网的自然语言处理课，我买了课，他讲得很烂，水平很低，骗人钱，告他
