### ISSUE TITLE
seq2seq-ner效果询问

### ISSUE THREAD

**Issue by qichaotang** [qhduan/just_another_seq2seq#16]
hi,
    看到您使用 seq2seq model 来做 ner ，请问您最后得出的效果怎么样？相比与 Bi-lstm-crf 之类，
thanks,

**Comment by qhduan** [comment]
直接的seq2seq容易过拟合，效果一般，这个repo里面也有crf的实现

**Comment by qichaotang** [comment]
看到了，赞，不过这也是一种思路，thanks
