### ISSUE TITLE
用其他的数据训练，一个epoch中step数减少太多

### ISSUE THREAD

**Issue by niliusha123** [qhduan/just_another_seq2seq#29]
您好，
我用其他的数据集训练，该训练集的总条数为1363683，部分数据如下
```
- E
- M 读大学
- M 没有什么过不去的
- E
- M 我不是你爸
- M 是！否则妈妈怎么老和我说爱他呢，我都吃醋了
```
在训练的过程中，每个epoch的总数为1085，

而使用您给的数据集的总条数4268087，每个epoch数目可以达到26158，
26158/1085>4268087/1363683, 这个差距比较大，这是什么原因，难道是数据集没有加 “/” 的原因吗

**Comment by RaymondJSu** [comment]
@niliusha123 你好請問後來問題怎麼解決的呢?
